<Project>

    <!-- Bootstrap -->
    <PropertyGroup>
        <TmlBuildBootstrapFeatures>tomat.environmentmodlist;tomat.enablemod;lolxd87.splashskip;tomat.assethotreloading;ppeb.netcoredbg</TmlBuildBootstrapFeatures>
    </PropertyGroup>

    <!-- Publicizer -->
    <PropertyGroup>
        <PublicizerClearCacheOnClean>true</PublicizerClearCacheOnClean>
    </PropertyGroup>
	<ItemGroup>
		<Publicize Include="FNA" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
        <Publicize Include="ReLogic" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

    <!-- Global usings -->
    <ItemGroup>
        <Using Include="System"/>
        <Using Include="Terraria"/>
        <Using Include="Terraria.ID"/>
        <Using Include="Terraria.ModLoader"/>
        <Using Include="Microsoft.Xna.Framework"/>
        <Using Include="Microsoft.Xna.Framework.Graphics"/>
    </ItemGroup>

</Project>
 